config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'teams#index'
  resources :teams
  resources :transfers
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :transfers, dependent: :destroy
  has_many :teams, through: :transfers
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :transfers, dependent: :destroy
  has_many :players, through: :transfers

  validates :name, uniqueness: true
  FORMATIONS = %w(4-4-2 3-4-3 3-5-2)
  validates :formation, inclusion: { in: FORMATIONS }

  def goalkeepers_num
    2
  end

  def defenders_num
    formation.split('-').first.to_i + 1
  end

  def midfielders_num
    formation.split('-').second.to_i + 1
  end

  def forwards_num
    formation.split('-').third.to_i + 1
  end

  def goalkeepers
    transfers.select { |t| t.player_position == 'GK' }.map &:player
  end

  def defenders
    transfers.select { |t| t.player_position == 'D' }.map &:player
  end

  def midfielders
    transfers.select { |t| t.player_position == 'M' }.map &:player
  end

  def forwards
    transfers.select { |t| t.player_position == 'F' }.map &:player
  end

  def current_budget
    players.reduce(budget) { |players_cost, player| players_cost - player.value }
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :team
  belongs_to :player

  def player_position
    player = Player.find(player_id)
    player.position
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.user_id = current_user.id

    respond_to do |format|
      if @team.save!
        format.js
        format.html { redirect_to new_transfer_path }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    @team.update(budget: params[:new_budget])
    # raise
    redirect_to @team
  end

  private

  def team_params
    params.require(:team).permit(:name, :formation, :budget, :points)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def new
    @transfer = Transfer.new
    @transfers = Transfer.all
    @goalkeepers = Player.where(position: 'GK').sort { |a, b| a.surname <=> b.surname }
    @defenders = Player.where(position: 'D').sort { |a, b| a.surname <=> b.surname }
    @midfielders = Player.where(position: 'M').sort { |a, b| a.surname <=> b.surname }
    @forwards = Player.where(position: 'F').sort { |a, b| a.surname <=> b.surname }
  end

  def create
    @transfer = Transfer.new
    @transfer.team_id = params[:team_id]
    @transfer.player_id = params[:player_id]
    respond_to do |format|
      if @transfer.save!
        format.js
        format.html { redirect_to new_transfer_path }
        # raise
      else
        format.html { render 'new' }
      end
    end
  end

  def destroy
    @transfer = Transfer.find(params[:id])
    @transfer.destroy
    redirect_to new_transfer_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyFootball2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/transfers/create.js.erb
// const team = document.getElementBtId('team-players-list')
// let newPlayer = document.createElement('div')
// newPlayer.innerHTML = <%= @transfer.player.name %>
// team.appendChild(newPlayer)
// console.log(hi!)
$("<%= escape_javascript(render @transfer) %>").appendTo("#team-players-list");

app/views/transfers/new.html.erb
<div class="all-players-list">
  <% @players.each_with_index do |player, i| %>
    <%= link_to player.name, transfers_path(player_id: player.id, team_id: current_user.team.id), method: 'POST' %>
  <% end %>
</div>

<div id="team-players-list">
  <% @transfers.each do |t| %>
    <p><%= t.player.name %></p>
  <% end %>
</div>